meta:
  title: Viator Partner API v1
  description: Developer resources for Viator Partner API v1 (merchant)
  siteUrl: https://viator.com
headerIcon: developer-portal/images/viator-partners.png
enableToc: true
oasDefinitions:
  petstore: ./openapi/vapi/openapi.yaml
  # petstore: ./openapi/vapi/openapi.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto:300,400,600,700
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
#ga:
  # you can use any options here from https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/
  # note that GA doesn't work in DEV
#  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:

  # - label: Training exercises
  #   page: developer-portal/index.md

  # - label: Markdown exercises
  #   page: developer-portal/markdown.md
  
  # - label: External docs
  #   icon: ./images/redocly-icon-white.png
  #   href: https://docs.redoc.ly/developer-portal/introduction/

  # - label: Favorite website
  #   href: https://redoc.ly
  
  - search: true
  

footer:
  copyrightText: Copyright © Redocly LLC 2019-2020. All right reserved.
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          href: 'https://redoc.ly/subscription-agreement/'
        - label: Privacy Notice
          href: 'https://redoc.ly/privacy-policy/'
        - label: Cookie Notice
          href: 'https://redoc.ly/privacy-policy/'
    
    - group: Product
      items:
        - label: Reference docs
          href: 'https://docs.redoc.ly/api-reference-docs/getting-started/'
        - label: Developer portal
          href: 'https://docs.redoc.ly/developer-portal/introduction/'
        - label: CI/CD workflows
          href: 'https://docs.redoc.ly/ci-cd-workflows/'

    - group: Support
      items:
        - label: FAQ
          page: faq.md
        - label: Contact us
          page: contact.mdx
