get:
  tags:
    - Product services
  summary: /product/reviews
  operationId: productReviews
  description: >
    Get user-submitted reviews of a product


    **Note**: 

    - The number of reviews that you can obtain via this service will depend on
    whether your account is limited in terms of the number of reviews you are
    entitled to receive. 

    - The number of reviews available through this service is given in the
    `reviewCount` element in the response from
    [/product](#operation/product)

    - Please speak to your account manager if you wish to receive more reviews.
    If your account is not limited, you will be able to receive all available
    reviews for this product.

    - Only reviews in the language specified in the Accept-Language request
    header will be returned


    **Example:** "Get the first three reviews for product `5010SYDNEY` sorted by
    rating in ascending order":


    ```javascript

    https://viatorapi.sandbox.viator.com/service/product/reviews?sortOrder=REVIEW_RATING_A&topX=1-3&code=5010SYDNEY&showUnavailable=false

    ```
  parameters:
    - $ref: ../components/parameters/acceptLanguage.yaml
    - $ref: ../components/parameters/sortOrder_REVIEW.yaml
    - $ref: ../components/parameters/topX.yaml
    - $ref: ../components/parameters/code.yaml
    - $ref: ../components/parameters/showUnavailable.yaml
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/basicErrorModel.yaml
              - type: object
                properties:
                  data:
                    type: array
                    description: '**array** of review objects'
                    items:
                      $ref: ../components/schemas/reviewObject.yaml
          examples:
            '1':
              $ref: ../components/examples/product-reviews-example.yaml
