summary: 5010SYDNEY
value:
  errorReference: null
  data:
    supplierName: Big Bus Tours
    currencyCode: USD
    catIds:
      - 6
      - 12
    subCatIds:
      - 97
      - 98
      - 5330
      - 26963
      - 32024
      - 45
    webURL: null
    specialReservationDetails: null
    sslSupported: false
    panoramaCount: 0
    merchantCancellable: true
    bookingEngineId: UnconditionalBE
    onRequestPeriod: null
    primaryGroupId: null
    pas: null
    available: true
    productUrlName: Sydney-and-Bondi-Hop-on-Hop-off-Tour
    primaryDestinationUrlName: Sydney
    voucherRequirements: You can present either a paper or an electronic voucher for this activity.
    tourGradesAvailable: true
    hotelPickup: false
    userPhotos:
      - sortOrder: 1
        ownerName: Husker1k
        ownerCountry: null
        productTitle: Big Bus Sydney and Bondi Hop-on Hop-off Tour
        productUrlName: Sydney-and-Bondi-Hop-on-Hop-off-Tour
        ownerAvatarURL: null
        sslSupported: false
        productCode: 5010SYDNEY
        caption: <p>Carl and Karen meeting a new friend at the Wildlife park.</p>
        thumbnailURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/e4/dsc00471-photo_1909732-133sq.jpg
        ownerId: 1755909
        editorsPick: true
        timeUploaded: '2012-02-07'
        photoURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/e4/dsc00471-photo_1909732-770tall.jpg
        photoId: 1909732
        photoHiResURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/e4/dsc00471-photo_1909732-1536tall.jpg
        photoMediumResURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/e4/dsc00471-photo_1909732-260tall.jpg
        title: DSC00471
      - sortOrder: 2
        ownerName: Kylie G
        ownerCountry: Australia
        productTitle: Big Bus Sydney and Bondi Hop-on Hop-off Tour
        productUrlName: Sydney-and-Bondi-Hop-on-Hop-off-Tour
        ownerAvatarURL: null
        sslSupported: false
        productCode: 5010SYDNEY
        caption: Sydney Opera House
        thumbnailURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/f2/sydney-opera-house-photo_997106-133sq.jpg
        ownerId: 288013
        editorsPick: true
        timeUploaded: '2009-07-22'
        photoURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/f2/sydney-opera-house-photo_997106-770tall.jpg
        photoId: 997106
        photoHiResURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/f2/sydney-opera-house-photo_997106-1536tall.jpg
        photoMediumResURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/f2/sydney-opera-house-photo_997106-260tall.jpg
        title: Sydney Opera House
    reviews:
      - sortOrder: 1
        ownerName: esperanza h
        ownerCountry: null
        productTitle: Big Bus Sydney and Bondi Hop-on Hop-off Tour
        productUrlName: Sydney-and-Bondi-Hop-on-Hop-off-Tour
        ownerAvatarURL: null
        sslSupported: false
        viatorNotes: ''
        productCode: 5010SYDNEY
        submissionDate: '2020-01-16'
        rating: 5
        review: >-
          <p>Excellent way of visiting the city! It’s the only way to see
          atttactions in Sydney as I only have three days to stay . The next day
          I went back to Bondi beach to spend half of my day for the birthday of
          my son. Went to Iceberg Club overlooking the beach with surfers. It’s
          the best view you can get while having lunch! Walked along the coast
          to enjoy the magnificent view. I plan to go back again to this
          beautiful city. Spent sometime at the opera house area where there’s
          plenty of nice cafes to eat while admiring the view!</p>
        publishedDate: '2020-01-16'
        ownerId: 32351278
        viatorFeedback: ''
        reviewId: 67907371
      - sortOrder: 2
        ownerName: tomzak21
        ownerCountry: null
        productTitle: Big Bus Sydney and Bondi Hop-on Hop-off Tour
        productUrlName: Sydney-and-Bondi-Hop-on-Hop-off-Tour
        ownerAvatarURL: >-
          http://cache-graphicslib.viator.com/graphicslib/media/f5/tomzak21-account_47925237-45sq.jpg
        sslSupported: false
        viatorNotes: ''
        productCode: 5010SYDNEY
        submissionDate: '2020-01-09'
        rating: 5
        review: >-
          <p>Love The Big Bus, Hop On / Hop Off Tour Company! This is the way to
          see just about all the key areas and tourist attractions. You don't
          have to rent a car and they are actually comfortable. We also did a
          Hop On, Hop Off in Budapest, Hungary and that was great also, saw all
          the major attractions!</p>


          <p>  They provide you with earbuds and there are 6+ languages that you
          can choose. Being in Sydney, there was Chinese, Korean, Japanese,
          along with French, Spanish, English and I believe German.</p>


          <p>  There is also a "package deal" in which you can purchase a pass
          to other attractions along the route.. like Wildlife Sydney Zoo,
          Madame Tussaud's, Sydney Eye. You can buy a 2, 3 or 4 attraction pass
          in which The Big Bus is one of the attractions.</p>


          <p>  Love The Big Bus! If you want a quick tour or spend a couples
          days of exploring, this is the way to go!</p>


          <p>  Only complaint... the drop off  and  pick up spots could be
          better labeled. They should put there logo on a sign and make it
          noticeable. Some stops had some kind of sign, but there were a few
          stops that we weren't sure we were in the right spot. It wound up that
          we were in the correct spot. Addresses are listed in the provided  in
          the pamphlet / flyer provided.</p>
        publishedDate: '2020-01-09'
        ownerId: 47925237
        viatorFeedback: ''
        reviewId: 67480203
    videos: null
    tourGrades:
      - sortOrder: 1
        currencyCode: USD
        langServices:
          en/SERVICE_AUDIO: English - Audio
          de/SERVICE_AUDIO: German - Audio
          fr/SERVICE_AUDIO: French - Audio
          es/SERVICE_AUDIO: Spanish - Audio
          ja/SERVICE_AUDIO: Japanese - Audio
          ko/SERVICE_AUDIO: Korean - Audio
          zh/SERVICE_AUDIO: Chinese - Audio
        gradeCode: 24HOUR
        merchantNetPriceFrom: 29.52
        priceFrom: 36.97
        priceFromFormatted: $36.97
        merchantNetPriceFromFormatted: $29.52
        gradeTitle: '24 Hour Classic Ticket '
        gradeDepartureTime: ''
        gradeDescription: >-
          Unlimited use on Big Bus Sydney & Bondi Hop-on Hop-off Tour for 24
          hours from time of first use
        defaultLanguageCode: en
      - sortOrder: 2
        currencyCode: USD
        langServices:
          en/SERVICE_AUDIO: English - Audio
          de/SERVICE_AUDIO: German - Audio
          fr/SERVICE_AUDIO: French - Audio
          es/SERVICE_AUDIO: Spanish - Audio
          ja/SERVICE_AUDIO: Japanese - Audio
          ko/SERVICE_AUDIO: Korean - Audio
          zh/SERVICE_AUDIO: Chinese - Audio
        gradeCode: 48HOUR
        merchantNetPriceFrom: 39.53
        priceFrom: 49.5
        priceFromFormatted: $49.50
        merchantNetPriceFromFormatted: $39.53
        gradeTitle: '48 Hour Premium Ticket '
        gradeDepartureTime: ''
        gradeDescription: >-
          48 Hour Premium Ticket: Unlimited use on Big Bus Sydney & Bondi Tour
          for 48 hours from time of first use PLUS a guided walking tour of The
          Rocks, Syd
        defaultLanguageCode: en
      - sortOrder: 3
        currencyCode: USD
        langServices:
          en/SERVICE_AUDIO: English - Audio
          de/SERVICE_AUDIO: German - Audio
          fr/SERVICE_AUDIO: French - Audio
          es/SERVICE_AUDIO: Spanish - Audio
          ja/SERVICE_AUDIO: Japanese - Audio
          ko/SERVICE_AUDIO: Korean - Audio
          zh/SERVICE_AUDIO: Chinese - Audio
        gradeCode: DELUXE
        merchantNetPriceFrom: 55.05
        priceFrom: 68.93
        priceFromFormatted: $68.93
        merchantNetPriceFromFormatted: $55.05
        gradeTitle: 48 Hour Deluxe Bus and Cruise
        gradeDepartureTime: ''
        gradeDescription: >-
          Big Bus and Habour Cruise: Combine two great Sydney experiences into
          one with a hop-on hop off Big Bus Tours and a hop-on hop-off Sydney
          Harbour cruise <br/>Duration: 2 days: SPECIAL OFFER: EXTRA FREE DAY
          when you purchase a Deluxe ticket - have 3 days to explore Sydney not
          2. Limited time only.

          <br/>Complimentary Walking Tour: Complimentary English-speaking
          90-minute guided walking tour of “The Rocks” historic and harbourside
          precinct.
        defaultLanguageCode: en
      - sortOrder: 4
        currencyCode: USD
        langServices:
          en/SERVICE_AUDIO: English - Audio
          de/SERVICE_AUDIO: German - Audio
          fr/SERVICE_AUDIO: French - Audio
          es/SERVICE_AUDIO: Spanish - Audio
          ja/SERVICE_AUDIO: Japanese - Audio
          ko/SERVICE_AUDIO: Korean - Audio
          zh/SERVICE_AUDIO: Chinese - Audio
        gradeCode: TG1
        merchantNetPriceFrom: 71.74
        priceFrom: 89.81
        priceFromFormatted: $89.81
        merchantNetPriceFromFormatted: $71.74
        gradeTitle: 48Hour Deluxe PLUS Attractions
        gradeDepartureTime: ''
        gradeDescription: >-
          Hop-on Hop-Off and Attractions: 48hr Big Bus Tours, 1-day Hop-On
          Hop-Off Harbour Cruise, 4 Attractions: Tower Eye, Madame Tussauds,
          Wildlife Zoo, Aquarium<br/>Duration: 2 days: SPECIAL OFFER: EXTRA FREE
          DAY when you purchase a Deluxe ticket - have 3 days to explore Sydney
          not 2. Limited time only.

          <br/>Complimentary Walking Tours: Complimentary English-speaking
          guided walking tour of “The Rocks” historic and harbourside precinct.
        defaultLanguageCode: en
    ageBands:
      - sortOrder: 1
        ageFrom: 16
        ageTo: 99
        bandId: 1
        adult: true
        pluralDescription: Adults
        treatAsAdult: true
        count: 0
        description: Adult
      - sortOrder: 2
        ageFrom: 5
        ageTo: 15
        bandId: 2
        adult: false
        pluralDescription: Children
        treatAsAdult: true
        count: 0
        description: Child
      - sortOrder: 3
        ageFrom: 0
        ageTo: 4
        bandId: 3
        adult: false
        pluralDescription: Infants
        treatAsAdult: false
        count: 0
        description: Infant
    bookingQuestions: []
    passengerAttributes: null
    highlights: null
    salesPoints: []
    ratingCounts:
      '1': 38
      '2': 99
      '3': 198
      '4': 500
      '5': 770
    termsAndConditions: null
    merchantTermsAndConditions:
      termsAndConditions: >-
        For a full refund, cancel at least 24 hours in advance of the start date
        of the experience.
      merchantTermsAndConditionsType: 1
      amountRefundable: null
      cancellationFromTourDate:
        - dayRangeMin: 1
          dayRangeMax: null
          percentageRefundable: 100
          policyStartTimestamp: null
          policyEndTimestamp: null
        - dayRangeMin: 0
          dayRangeMax: 1
          percentageRefundable: 0
          policyStartTimestamp: null
          policyEndTimestamp: null
    maxTravellerCount: 9
    returnDetails: You may disembark at any of the available stops.
    specialOffer: ''
    itinerary: ''
    destinationId: 357
    translationLevel: 0
    additionalInfo:
      - Confirmation will be received at time of booking
      - Wheelchair accessible
      - >-
        When booking the 24 or 48 hour Family Pass, only the lead passenger name
        is required for a booking of up to 2 Adults and 2 children 16 years and
        under. At time of booking you only need to enter 1 adult to complete
        your booking
      - Infants aged 0 to 4 years travel free of charge
    voucherOption: VOUCHER_E
    applePassSupported: true
    productPhotos:
      - caption: Selfies at Bondi Beach
        photoURL: >-
          https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/09/c5/d3/87.jpg
        path: attractions-splice-spp-674x446/09/c5/d3/87.jpg
        supplier: SUPPLIER
      - caption: ''
        photoURL: >-
          https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/09/c5/d2/d1.jpg
        path: attractions-splice-spp-674x446/09/c5/d2/d1.jpg
        supplier: SUPPLIER
      - caption: ''
        photoURL: >-
          https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/94/40/f3.jpg
        path: attractions-splice-spp-674x446/07/94/40/f3.jpg
        supplier: SUPPLIER
      - caption: Sydney and Bondi Hop-On Hop-Off Tour
        photoURL: >-
          https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/09/c5/d2/d4.jpg
        path: attractions-splice-spp-674x446/09/c5/d2/d4.jpg
        supplier: SUPPLIER
      - caption: Bondi Beach
        photoURL: >-
          https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/09/c5/d2/c7.jpg
        path: attractions-splice-spp-674x446/09/c5/d2/c7.jpg
        supplier: SUPPLIER
      - caption: Visit icons
        photoURL: >-
          https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/90/5a/68.jpg
        path: attractions-splice-spp-674x446/07/90/5a/68.jpg
        supplier: SUPPLIER
      - caption: Big Bus App provides live tracking
        photoURL: >-
          https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/90/5a/6a.jpg
        path: attractions-splice-spp-674x446/07/90/5a/6a.jpg
        supplier: SUPPLIER
      - caption: The Rocks
        photoURL: >-
          https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/90/5a/7d.jpg
        path: attractions-splice-spp-674x446/07/90/5a/7d.jpg
        supplier: SUPPLIER
    departureTime: See itinerary
    departureTimeComments: ''
    departurePoint: You may start this tour at any of the stops listed.
    city: Sydney
    mapURL: null
    allTravellerNamesRequired: true
    operates: <p>Daily</p>
    exclusions:
      - Food and drinks
      - Admission
    description: >-
      <b>Itinerary</b><br><br><p><strong>Red Route - Sydney
      Icons</strong></p><p>Route Duration: 2 hours</p><div>Stops on the Red
      Route - Sydney Icons:</div><ul><li>T Galleria x Petal met Sugar - Circular
      Quay, George St, cnr Alfred St. (opp DFS Galleria)</li>

      <li>Martin Place Station, Elizabeth St, Stand E - Sydney Tower/
      Westfield</li>

      <li>1 William St - Australian Museum</li>

      <li>William St at Palmer St - William St, Kings Cross</li>

      <li>121 Darlinghurst Rd - Kings Cross Train Station on Darlinghurst
      Rd.</li>

      <li>123-125 MacLeay St - El Alamein Fountain</li>

      <li>2 Bourke St - Cowper Wharf Rd, outside the Woollomooloo Hotel</li>

      <li>2A Macquarie St - Sydney Opera House</li>

      <li>Macquarie Street - Botanical Garden, Scenic Walk to Mrs Macquarie
      Chair</li>

      <li>State Library of New South Wales - State Library</li>

      <li>Prince Albert Rd opp College St - Hyde Park</li>

      <li>Greyhound Australia - Central Station, Pitt Street, Bus Bay 18</li>

      <li>Powerhouse Museum, Harris St - Powerhouse Museum</li>

      <li>Fish Market - Harris St, cnr Pyrmont Bridge Rd</li>

      <li>Marquee Sydney - The Star Casino</li>

      <li>Maritime Museum</li>

      <li>ICC Sydney</li>

      <li>Chinese Garden of Friendship</li>

      <li>SEA LIFE Sydney Aquarium</li>

      <li>ibis Sydney King Street Wharf - Kings Street Wharf</li>

      <li>Hickson Road</li>

      <li>Dawes Point - Sydney Harbour Bridge</li>

      <li>The Rocks</li></ul><div>Attractions on the Red Route - Sydney
      Icons:</div><p>Hyde Park Barracks / Australian Museum / Sea Life Sydney
      Aquarium / Darling Harbour / The Rocks / Bondi Beach / Sydney Harbour
      Bridge / Royal Botanic Garden Sydney / Sydney Town Hall / Hyde Park /
      Circular Quay / City Sightseeing Sydney / Madame Tussauds Sydney / Big Bus
      Sydney</p><p><i>Operates:</i> 1st bus departs from Stop 1 Circular Quay at
      8.30am.

      Frequency every 20 minutes

      Last bus departs from stop 1 at 6.30pm</p><p><strong>Blue Route - Bondi
      Lifestyle</strong></p><p>Route Duration: 2 hours</p><div>Stops on the Blue
      Route - Bondi Lifestyle:</div><ul><li>492 Pitt St - Central Station, Pitt
      Street, Bus Bay 18</li>

      <li>1 William St - Australian Museum </li>

      <li>Paddington Town Hall, Oxford St</li>

      <li>Oxford St opp Moncur St</li>

      <li>Bondi Beach</li>

      <li>North Bondi Beach, Campbell Pde</li>

      <li>Rose Bay</li>

      <li>Double Bay</li></ul><div>Attractions on the Blue Route - Bondi
      Lifestyle:</div><p>Paddington Markets / Centennial Park / Bondi Beach /
      Rose Bay / Double Bay</p><p><i>Operates:</i> 1st bus departs from Stop 1
      Circular Quay at 9.30am.

      Frequency every 30 minutes

      Last bus departs from stop 1 at 6.30pm</p>
    inclusions:
      - Choice of 24 hour or 48 hour pass
      - >-
        Pre-recorded commentary in English, French, Spanish, German, Italian,
        Mandarin, Japanese, Korean
      - Free wifi onboard
    location: 'The Rocks, Australia'
    country: Australia
    region: New South Wales
    shortTitle: Big Bus Sydney and Bondi Hop-on Hop-off Tour
    specialOfferAvailable: false
    price: 36.97
    supplierCode: '5010'
    thumbnailHiResURL: >-
      https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/94/40/f3.jpg
    primaryDestinationName: Sydney
    thumbnailURL: >-
      https://hare-media-cdn.tripadvisor.com/media/attractions-splice-spp-154x109/07/94/40/f3.jpg
    onSale: false
    photoCount: 124
    reviewCount: 1605
    primaryDestinationId: 357
    merchantNetPriceFrom: 29.52
    priceFormatted: $36.97
    rrp: 0
    rrpformatted: ''
    videoCount: 1
    rating: 4.5
    savingAmountFormated: ''
    specialReservation: false
    savingAmount: 0
    merchantNetPriceFromFormatted: $29.52
    essential: null
    admission: null
    duration: 2 hours
    shortDescription: >-
      Explore Sydney and Bondi Beach on this hop-on hop-off sightseeing tour,
      which takes you by double-decker bus to 34 stops around the city including
      Sydney Opera House, Sydney Harbour Bridge, Darling Harbour, Bondi Beach
      and more. Enjoy unobstructed views and recorded commentary on board.
      Simply hop off to walk around and sightsee in depth. Your ticket is valid
      for 24 or 48 hours, so you can experience Sydney and Bondi's most
      noteworthy attractions, sights, and shopping and dining areas at your own
      pace.
    title: Big Bus Sydney and Bondi Hop-on Hop-off Tour
    code: 5010SYDNEY
  dateStamp: '2020-02-06T18:15:04+0000'
  errorType: null
  errorCodes: []
  errorMessage: null
  errorName: null
  extraInfo: {}
  extraObject: null
  success: true
  totalCount: 1
  errorMessageText: null
  vmid: '331001'
